version: 2

jobs:
    build:
        docker:
            - image: nixos/nix:2.19.2
        steps:
            #- run:
            #    name: Update nixos-20.09
            #    command: |
            #        nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
            #        nix-channel --update
            #- run:
            #    name: Forfeit freedom
            #    command: |
            #        mkdir -p ~/.config/nixpkgs
            #        echo "{allowUnfree = true;}" >> ~/.config/nixpkgs/config.nix
            #- run:
            #    name: Install Utils
            #    command: |
            #        nix-env -u
            #        nix-env -i coreutils openssh git bash cachix
            - checkout
            - run:
                name: Configure Nix
                command: |
                    mkdir -p /etc/nix
                    echo "build-cores = 2" >> /etc/nix/nix.conf
            #- run:
            #    name: Setup Cachix
            #    command: cachix use rdf
            - run:
                name: Build rdf
                command: nix-shell --pure --run "cabal update && cabal build -j$(nproc)"

workflow:
    version: 2
    build-and-test:
        jobs:
            - build
